openapi: 3.1.0
servers:
  - url: https://{host}
    variables:
      host:
        default: realm.redocly.com
        description: Server host.
    description: Production main server.
info:
  title: Realm
  version: 1.0.0
  description: API for Realm service.
  termsOfService: https://redocly.com/subscription-agreement
  license:
    name: Redocly
    url: https://redocly.com/subscription-agreement

security:
  - ApiKey: []

tags:
  - name: health
    description: Health check operations.
  - name: Cors proxy
    description: Internal cors proxy operations.
  - name: Entities
    description: Catalog entities operations.
  - name: BFF Entities
    description: Catalog entities for frontend operations.
  - name: Entity relations
    description: Catalog entities relations operations.

paths: {}

components:
  securitySchemes:
    ApiKey:
      type: apiKey
      name: X-API-Key
      in: header
